Just disable unit test on centos-stream
The collect ignore does not work with older pytest:

```
  File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 252, in _verify_hook
    raise PluginValidationError(
pluggy.manager.PluginValidationError: Plugin '/var/ARTIFACTS/work-basiciy0u5a0r/plans/basic/discover/default-0/tests/conftest.py' for hook 'pytest_ignore_collect'
hookimpl definition: pytest_ignore_collect(collection_path, config) -> bool
Argument(s) {'collection_path'} are declared in the hookimpl but can not be found in the hookspec
```

Let's just skip centos stream for now.